// Mocks generated by Mockito 5.0.7 from annotations
// in simple_login/test/screens/login/login_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:simple_login/models/user_model.dart' as _i4;
import 'package:simple_login/service/user_service.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createUser(_i4.UserModel? user) =>
      (super.noSuchMethod(Invocation.method(#createUser, [user]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
  @override
  _i3.Future<String> login(String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#login, [username, password]),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  _i3.Future<bool> resetPassword(String? username, String? newPassword) =>
      (super.noSuchMethod(
          Invocation.method(#resetPassword, [username, newPassword]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}
